# Use an official Node.js runtime as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Parcel project
RUN npm run build

# Install a lightweight HTTP server to serve the built app
RUN npm install -g http-server

# Set the environment to use the dist folder generated by Parcel
WORKDIR /usr/src/app/dist

# Expose the port the app will run on
EXPOSE 8080

# Start the server to serve the files
CMD ["http-server", "-p", "8080"]
