# Use the official Node.js image as the base image
FROM node:16

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install all dependencies (including devDependencies for building)
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application using Parcel
RUN npm run build

# Install a lightweight HTTP server to serve the built app
RUN npm install -g http-server

# Set the environment to use the dist folder generated by Parcel
WORKDIR /usr/src/app/dist

# Expose the port the app will run on
EXPOSE 8080

# Start the server to serve the files
CMD ["http-server", "-p", "8080"]
